const types = {
    GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
    MORE_DATA_SUCCESS: 'MORE_DATA_SUCCESS',
    
    GET_DATA_FAILURE: 'GET_DATA_FAILURE',
    
    GET_COLLECTIONS_SUCCESS: 'GET_COLLECTIONS_SUCCESS',
    MORE_COLLECTIONS_SUCCESS: 'MORE_COLLECTIONS_SUCCESS',

    MAKE_REQUEST: 'MAKE_REQUEST',

    
    LOGOUT: 'LOGOUT',
  };
  
  export default types;
  